name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    strategy:
      matrix:
        include:
          - os: windows
            artifact_name: bitstamp-cli.exe
            arch: amd64
          - os: linux
            artifact_name: bitstamp-cli
            arch: amd64
          - os: darwin
            artifact_name: bitstamp-cli
            arch: amd64

    steps:
      - name: Install GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get version tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build
        id: build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          echo ${{ matrix.artifact_name }}
          echo ${{ steps.get_version.outputs.VERSION }}
          go build -o ${{ matrix.artifact_name }} -ldflags "-X main.version=${{ steps.get_version.outputs.VERSION }}"
          zip -m bitstamp-cli-${{ matrix.os }}-${{ matrix.arch }}.zip ${{ matrix.artifact_name }}
          echo ::set-output name=FILENAME::bitstamp-cli-${{ matrix.os }}-${{ matrix.arch }}.zip
          ls -la

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          file: ${{ steps.build.outputs.FILENAME }}
          asset_name: ${{ steps.build.outputs.FILENAME }}
          tag: ${{ steps.get_version.outputs.VERSION }}
          overwrite: true
          body: "bitstamp-cli ${{ steps.get_version.outputs.VERSION }}"
